repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: check-merge-conflict
      - id: trailing-whitespace

  - repo: https://github.com/psf/black
    rev: 21.8b0
    hooks:
      - id: black
        args: [--line-length=88]

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.931
    hooks:
      - id: mypy
        args: [--strict, --implicit-reexport, --show-error-codes]

  - repo: https://github.com/pycqa/flake8
    rev: 4.0.1
    hooks:
    -   id: flake8
